name: CI/CD 

on:
  workflow_dispatch:

jobs:
 CI:
   runs-on: ubuntu-latest
   outputs:
    new_tag: ${{ steps.tag.outputs.new_tag }}
   steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the Docker image
        id: build
        run: |
          docker build -t nodejs:test .
          docker compose up -d

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: ./app

      - name: Run tests
        run: |
         npm test
         docker compose down
        working-directory: ./app

      # - name: Run Super-Linter.
      #   uses: super-linter/super-linter@v5
      #   env:
      #     VALIDATE_PYTHON_PYLINT: true
      #     DEFAULT_BRANCH: main
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Bump version and push tag
        id: tag
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.access_token }}
          WITH_V: false
          DEFAULT_BUMP: patch
          INITIAL_VERSION: 1.0.0
          DEFAULT_BRANCH: main
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: davidalkobi/nodeapp:${{ steps.tag.outputs.new_tag }}

 CD:
    needs: CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: clone the gitops repo
      id: clone-the-gitops-repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.access_token}}
        repository: DavidAlkobi/Infra_Nodejs
        ref: main

    - name: do some gitops
      id: update-the-gitops-repo
      if: ${{ github.ref == 'refs/heads/main'}}
      run: |
        cd k8s
        tag=${{needs.CI.outputs.new_tag}}
        sed -i "s|davidalkobi/nodeapp:.*|davidalkobi/nodeapp:$tag|" deploy-app.yaml
        git config --global user.email "davidalk3@gmail.com"
        git config --global user.name "github actions"
        git add deploy-app.yaml
        git commit -m "update the image tag to test"
        git push origin main

   
    - name: Deploy to staging
      uses: medyagh/setup-minikube@master
    
    - name: Try the cluster !
      run: kubectl get pods -A        
    
    - name: Deploy to minikube
      run: |
        cd k8s
        kubectl apply -f .
        
    - name: Take a nap
      run: sleep 30
    
    - name: Check pods
      run: |
        kubectl get pods
  
    - name: Test Login To App
      run: |
        docker images
        minikube service list
        kubectl get pods
  
    
