name: deploy to staging

on:
  workflow_dispatch:

jobs:
 Staging:

  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v3
  - name: clone the gitops repo
    id: clone-the-gitops-repo
    uses: actions/checkout@v3
    with:
      token: ${{ secrets.access_token}}
      repository: DavidAlkobi/Infra_Nodejs
      ref: main
  
  - name: Start minikube
    uses: medyagh/setup-minikube@master
  
  - name: Try the cluster !
    run: kubectl get pods -A        
  
  - name: Deploy to minikube
    run: |
      kubectl apply -f .
      
  - name: Take a nap
    run: sleep 30
  
  - name: Check pods
    run: |
      kubectl get pods

  - name: Test Login To App
    run: |
      docker images
      minikube service list
      kubectl get pods
   
